### ISSUE TITLE
ArchLinux does not like /usr/lib64

### ISSUE THREAD

**Issue by roman-neuhauser** [spmfilter/libcmime#1]
i packaged libcmime-0.1.13 for ArchLinux, ran [namcap](https://wiki.archlinux.org/index.php/namcap) on the result, got

  libcmime E: ELF file ('usr/lib64/libcmime.so.0.1.13') outside of a valid path.

since i'm quite ignorant about CMake, can you suggest an invocation that would make it use `/usr/lib`?  the following snippet leads to the described unwanted behavior:

```
  mkdir "$srcdir/build"
  cd "$srcdir/build"
  cmake "$srcdir/$pkgname-$pkgver" -DPREFIX:STRING=/usr
  make
```

**Comment by axelsteiner** [comment]
I've just tested cmake on ArchLinux with following settings in build.properties:

> set(PREFIX /usr/)
> set(CMAKE_INSTALL_LIBDIR lib)

And `make install` used the correct library dir:
> /usr/bin/cmake -P cmake_install.cmake
> -- Install configuration: ""
> -- Installing: /usr/lib/pkgconfig/libcmime.pc
> -- Installing: /usr/lib/libcmime.so.0.1.16
> -- Installing: /usr/lib/libcmime.so.0.1
> -- Installing: /usr/lib/libcmime.so
> -- Installing: /usr/include/cmime/cmime_address.h
> -- Installing: /usr/include/cmime/cmime_base64.h
> -- Installing: /usr/include/cmime/cmime_config.h
> -- Installing: /usr/include/cmime/cmime_header.h
> -- Installing: /usr/include/cmime/cmime_list.h
> -- Installing: /usr/include/cmime/cmime_message.h
> -- Installing: /usr/include/cmime/cmime_part.h
> -- Installing: /usr/include/cmime/cmime_qp.h
> -- Installing: /usr/include/cmime/cmime_string.h
> -- Installing: /usr/include/cmime/cmime_util.h
> -- Installing: /usr/include/cmime.h

So there is no need to modify cmake configuration.
