### ISSUE TITLE
Not supported for Windows?

### ISSUE THREAD

**Issue by spartucus** [spmfilter/libcmime#13]
Great work! It is small and neat, it would be a cool library for mime.

I'd like to use libcmime on windows, whether in lib/dll mode or pure source. 
But when I try use source code in my project, it failed on building with quite errors, most of them are OS-related, but some of them are build related, such as `FILE_EXECUTABLE` in `cmime_util_get_mimetype`. I wonder if there are any chances that libcmime works on Windows.
Thanks.

**Comment by axelsteiner** [comment]
At the moment libcmime is not portable to Windows. The `FILE_EXECUTABLE` definition stores the path to the `file` binary of Linux/Unix systems, which is used to determine the type of given files. So it would need a replacement for Windows with corresponding preprocessor definitions.

If someone is willing to port libcmime to Windows, I would gladly merge the code.

**Comment by spartucus** [comment]
Thanks, I would love to make some contributes.
