### ISSUE TITLE
Need to find a way to extract/decode body text

### ISSUE THREAD

**Issue by vflyson** [spmfilter/libcmime#14]
Nice library, using it in one of my projects.

I couldn't find a way to easily separate message body from its headers (say I only need to extract plaintext from each email).
Some emails are HTML, some are encoded in base64.
Is it a planned feature or I overlooked it somehow in the code?

Thank you.

**Comment by axelsteiner** [comment]
The message header are already stored separate in `CMimeMessage_T` struct. All mime parts of a message (or plain text body) are also stored in `CMimeMessage_T` struct as `CMimeList_T *parts` pointer, see http://libcmime.org/struct_c_mime_message___t.html. If you need to get the content of a mime part, you could easily iterate them (see http://libcmime.org/cmime__list_8h.html) and use `cmime_part_to_string()` to get the actual content of the mime part.
