### ISSUE TITLE
Encoding for non-ascii fields?

### ISSUE THREAD

**Issue by klopp** [spmfilter/libcmime#8]
Now:

```
Subject: пример
From: кто-то <from@test.com>
```

Valid:

```
Subject: =?UTF-8?B?0J/RgNC40LzQtdGA?=
From: =?UTF-8?B?0LrRgtC+LdGC0L4=?=  <from@test.com>
```

**Comment by axelsteiner** [comment]
The functions cmime_message_set_sender(), cmime_message_set_subject() and cmime_message_add_recipient() do not encode non 7-bit characters at the moment. New functions for this feature will be added soon.
