### ISSUE TITLE
Example with embedding an image

### ISSUE THREAD

**Issue by shaun-edwards** [spmfilter/libcmime#9]
Do you have an example with embedding an image?  I followed the example [here](http://libcmime.org/create_mime_message_part_from_file_8c-example.html) but my image is in memory not stored as a file.

**Comment by axelsteiner** [comment]
You could encode the image with base64 in memory and use _cmime_part_from_string()_, then you don't have to use a temp file. Additionally you need to set the content part headers with _cmime_part_set_content_type()_, _cmime_part_set_content_transfer_encoding()_, _cmime_part_set_content_disposition()_ and _cmime_part_set_content_id()_

**Comment by shaun-edwards** [comment]
Thanks for the response...I will try that
